# Generated by Django 4.1.3 on 2022-11-04 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_alter_videos_options_rename_slug_videos_cato_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slug',
            new_name='cato_slug',
        ),
        migrations.RenameField(
            model_name='videos',
            old_name='cato_slug',
            new_name='slug',
        ),
    ]
