# Generated by Django 4.1.3 on 2022-11-04 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_rename_slug_category_cato_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cato_slug',
            new_name='slug',
        ),
    ]
