# Generated by Django 4.1.3 on 2022-11-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_videos_video_url_alter_videos_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='video_url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
