# Generated by Django 4.1.3 on 2022-11-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_alter_videos_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='video_url',
            field=models.URLField(default=''),
        ),
    ]
