# Generated by Django 4.1.3 on 2022-11-15 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_alter_videos_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('Image', models.URLField()),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
